export const SET_PROJECTS = 'SET_PROJECTS'
export const UPDATE_BRANCH = 'UPDATE_BRANCH'
export const LOCK_ENV = 'LOCK_ENV'
export const ADD_QUEUE = 'ADD_QUEUE'
export const SET_ENV_USERS = 'SET_ENV_USERS'